### ISSUE TITLE
Cross Origin Error on fresh install

### ISSUE THREAD

**Issue by orcu** [aureliojargas/moneylog#29]
After doing a fresh install following the guidelines and txt file structure at https://aurelio.net/moneylog/beta/, the html file gets stuck showing "Loading txt/data-pt.txt...".  Web console shows the following errors at "filesystem.js":38 :

On Firefox:
SecurityError: Permission denied to access property "document" on cross-origin object

On Chromium:
Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at HTMLIFrameElement.iframe.onload 

Similar problem on MoneyLog4 on line 876, when external data file is configured. Both versions, MoneyLog Portable and MoneyLog4, work fine when data file is included in the html file.

**Comment by aureliojargas** [comment]
Hi @orcu, 

Unfortunately, that's the browser security policy, it's forbidden to load exra local files. It used to work many years ago, when MoneyLog was first implemented, but not anymore.

As you already noticed, embedding the data into HTML works fine (with the caveat that you have to escape the special chars `&`, `<` and `>`).

Another option, if you're a Google Drive user, is the updated Cloud version, available in https://moneylog.aurelio.net/ (the sources are in this repository).
