### ISSUE TITLE
https://github.com/aureliojargas/moneylog.git

### ISSUE THREAD

**Issue by anselmobattisti** [aureliojargas/moneylog#6]
Está dando erro 500!

O que posso fazer para ajudar a resolver? 

Está precisando de um server pra rodar isso?

**Comment by aureliojargas** [comment]
Oi Anselmo,

A versão Cloud do MoneyLog está fora do ar por causa das mudanças na API do Dropbox 😢 

Precisamos de ajuda sim, dá uma olhada na issue do problema : https://github.com/xupisco/MoneyLog-Cloud/issues/7

Vou fechar esta aqui, ok?
